### ISSUE TITLE
Breaking changes to VSMenuModHelper cause the game to crash on startup

### ISSUE THREAD

**Issue by CallMeEchoCodes** [LeCloutPanda/DebugMode#5]
**Mod version:** v1.0.5
**Game version:** 1.6.104
**Melon loader version:** v0.6.1

**Issue:** Breaking changes to [VSMenuModHelper](https://github.com/nwfistere/VSMenuModHelper) cause the game to crash on startup

[Latest.log](https://pastebin.com/KwxR3Jvy)

**Comment by LeCloutPanda** [comment]
There was [this](https://github.com/LeCloutPanda/DebugMode/releases/tag/v1.0.7-a) but the reason I set it to alpha was because I knew that [this](https://github.com/nwfistere/VSMenuModHelper/releases/tag/v1.2.0) was in the works so I will update when I can but that won't be for a day or two as I am very busy working on projects.

**Comment by Ashuraman666** [comment]
So is this mod not being worked on anymore?
